apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "go-reminders.fullname" . }}
  labels:
    app.kubernetes.io/name: {{ include "go-reminders.name" . }}
    helm.sh/chart: {{ include "go-reminders.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "go-reminders.name" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "go-reminders.name" . }}
        app.kubernetes.io/instance: {{ .Release.Name }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: {{ .Values.container.port.name }}
              containerPort: {{ .Values.container.port.containerPort }}
              protocol: TCP
          livenessProbe:
            httpGet:
              path: {{ .Values.container.livenessProbe.path }}
              port: go-reminders
          readinessProbe:
            httpGet:
              path: {{ .Values.container.readinessProbe.path }}
              port: go-reminders
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          env:
            {{- range $item := $.Values.container.env }}
            - name: {{ $item.name }}
              value: {{ $item.value }}
            {{- end }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      imagePullSecrets:
        - name: go-reminders-registry-creds

    {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
