apiVersion: v1
kind: Service
metadata:
  name: {{ include "go-reminders.fullname" . }}
  labels:
    app.kubernetes.io/name: {{ include "go-reminders.name" . }}
    helm.sh/chart: {{ include "go-reminders.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: go-reminders
      protocol: TCP
      name: go-reminders
  selector:
    app.kubernetes.io/name: {{ include "go-reminders.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
